import os
import sys
import random

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), ".")))

from app.database import SessionLocal
from app.models.academic import Subject, SyllabusEntry
from app.models.content import Note, QARepository, PreviousQuestion, Video
from app.models.user import User

def seed_materials():
    db = SessionLocal()
    
    # Get standard user id
    default_user = db.query(User).first()
    user_id = default_user.id if default_user else None

    subjects = db.query(Subject).all()
    print(f"Starting seed for {len(subjects)} subjects...")

    counts = {"notes": 0, "videos": 0, "qa": 0, "pyqs": 0}

    for subject in subjects:
        units = db.query(SyllabusEntry).filter_by(subject_id=subject.id).all()
        
        # 1. Generate PYQs (Previous Year Questions) per subject
        existing_pyqs = db.query(PreviousQuestion).filter_by(subject_id=subject.id).count()
        if existing_pyqs == 0:
            for year in [2022, 2023, 2024]:
                for exam in ["midsem", "endsem"]:
                    pyq = PreviousQuestion(
                        title=f"{year} {exam.capitalize()} Paper - {subject.name}",
                        year=year,
                        exam_type=exam,
                        subject_id=subject.id,
                        semester_id=subject.semester_id,
                        file_path=None,
                        external_link="https://www.example.com/pyq.pdf",
                        source_url="https://www.bput.ac.in/exam-papers"
                    )
                    db.add(pyq)
                    counts["pyqs"] += 1
            db.commit()

        # 2. Iterate units to create Notes, Videos, Q&As
        for unit in units:
            topic_str = f"Unit {unit.unit_number}: {unit.title}"
            
            # -- Create Notes --
            existing_notes = db.query(Note).filter_by(subject_id=subject.id, tags=topic_str).count()
            if existing_notes == 0:
                note = Note(
                    title=f"Comprehensive Notes: {topic_str}",
                    description=f"Detailed study material and reference content covering {unit.title} for {subject.name}.",
                    file_path=None,
                    external_link="https://example.com/notes.pdf",
                    subject_id=subject.id,
                    semester_id=subject.semester_id,
                    tags=topic_str,
                    uploaded_by=user_id,
                    source_type="imported"
                )
                db.add(note)
                counts["notes"] += 1

            # -- Create Videos --
            existing_videos = db.query(Video).filter_by(subject_id=subject.id, topic=topic_str).count()
            if existing_videos == 0:
                video = Video(
                    title=f"Lecture: {topic_str}",
                    description=f"In-depth video lecture explaining the intricacies of {unit.title}.",
                    subject_id=subject.id,
                    semester_id=subject.semester_id,
                    topic=topic_str,
                    youtube_url="https://www.youtube.com/embed/dQw4w9WgXcQ", 
                    thumbnail_url="https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
                    source="auto",
                    uploaded_by=user_id
                )
                db.add(video)
                counts["videos"] += 1

            # -- Create Q&A --
            existing_qa = db.query(QARepository).filter_by(subject_id=subject.id, topic=topic_str).count()
            if existing_qa == 0:
                qa1 = QARepository(
                    subject_id=subject.id,
                    semester_id=subject.semester_id,
                    topic=topic_str,
                    question=f"What are the fundamental concepts defined in {unit.title}?",
                    answer=f"The fundamental concepts involve standard theories, functional parameters, and practical applications that bridge {subject.name} principles to real-world architectures. (This is a comprehensive autogenerated expert answer.)",
                    difficulty="easy",
                    tags=topic_str,
                    created_by=user_id,
                    source="AI"
                )
                qa2 = QARepository(
                    subject_id=subject.id,
                    semester_id=subject.semester_id,
                    topic=topic_str,
                    question=f"Explain a complex scenario involving {unit.title} in a practical system.",
                    answer=f"Typically, a complex scenario integrates robust design metrics alongside scalable principles. Utilizing methodologies discussed in {unit.title}, engineers can drastically optimize load times and memory efficiency. (This is an advanced autogenerated expert answer.)",
                    difficulty="hard",
                    tags=topic_str,
                    created_by=user_id,
                    source="AI"
                )
                db.add_all([qa1, qa2])
                counts["qa"] += 2
        
        # Commit per subject to keep batches manageable
        db.commit()

    print("Seeding completed successfully!")
    print(f"Total Added -> Notes: {counts['notes']}, Videos: {counts['videos']}, Q&A: {counts['qa']}, PYQs: {counts['pyqs']}")
    db.close()

if __name__ == "__main__":
    seed_materials()
